SET TERMOUT ON

set colsep |

set pagesize 100 

set trimspool on

SET heading on

SET UNDERLINE OFF

spool results.lst;

alter session set "_ORACLE_SCRIPT"=true;

CREATE USER USUARIOPROYECTO IDENTIFIED BY USUARIOPRUEBA;

GRANT CONNECT TO USUARIOPROYECTO;

GRANT SELECT_CATALOG_ROLE TO USUARIOPROYECTO;

GRANT CREATE TABLE TO USUARIOPROYECTO;

GRANT UNLIMITED TABLESPACE TO USUARIOPROYECTO;

GRANT CREATE ANY JOB TO USUARIOPROYECTO;

GRANT CREATE PROCEDURE TO USUARIOPROYECTO;

SHOW ERRORS
spool OFF;